# add alias to bashrc
f="/etc/bash.bashrc"
echo -n "ls colors: "
if grep -q "alias ls=" $f; then   
   echo "already done"
else
   echo "alias ls=\"ls --color\"" >>$f
   echo "done"
fi

echo -n "ls -> ll alias: "
if grep -q "alias ll=" $f; then   
   echo "already done"
else
   echo "alias ll=\"ls -la\"" >>$f
   echo "done"
fi
